server:
    port: 8080
    servlet:
        context-path: /archetype

spring:
    application:
        name: recreating-archetype-sbng
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/archetype}
        username: ${SPRING_DATASOURCE_USERNAME:archetype}
        password: ${SPRING_DATASOURCE_PASSWORD:archetype}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update
